"""empty message

Revision ID: 0dec142a202f
Revises: aa8b54b8e5b1
Create Date: 2019-11-27 18:49:00.734308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dec142a202f'
down_revision = 'aa8b54b8e5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('checkOutTime', sa.DateTime(), nullable=True))
    op.drop_column('visitor', 'username')
    op.drop_column('visitor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('visitor', 'checkOutTime')
    # ### end Alembic commands ###
