"""empty message

Revision ID: 1345ad3adff4
Revises: 24589fcb3fa7
Create Date: 2019-11-29 03:34:38.167388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1345ad3adff4'
down_revision = '24589fcb3fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'host', ['vis_name'])
    op.drop_column('visitor', 'username')
    op.drop_column('visitor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'host', type_='unique')
    # ### end Alembic commands ###
