"""empty message

Revision ID: 24589fcb3fa7
Revises: 36dc9555d18a
Create Date: 2019-11-28 00:48:39.764359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24589fcb3fa7'
down_revision = '36dc9555d18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'host', ['vis_name'])
    op.drop_column('visitor', 'username')
    op.drop_column('visitor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'host', type_='unique')
    # ### end Alembic commands ###
