"""empty message

Revision ID: 2890f1e9e65a
Revises: 0dec142a202f
Create Date: 2019-11-27 20:27:34.241936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2890f1e9e65a'
down_revision = '0dec142a202f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor', 'username')
    op.drop_column('visitor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
