"""empty message

Revision ID: 35dd54184c32
Revises: 1345ad3adff4
Create Date: 2019-11-30 22:14:38.140798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35dd54184c32'
down_revision = '1345ad3adff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('visExpect', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visname_host_id'), 'visname', ['host_id'], unique=False)
    op.drop_column(u'host', 'vis_name')
    op.drop_column(u'visitor', 'username')
    op.drop_column(u'visitor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column(u'visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column(u'host', sa.Column('vis_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_visname_host_id'), table_name='visname')
    op.drop_table('visname')
    # ### end Alembic commands ###
