"""visitors table

Revision ID: 5071b3d32b1e
Revises: 
Create Date: 2019-11-26 23:05:22.544335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5071b3d32b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_email'), 'visitor', ['email'], unique=True)
    op.create_index(op.f('ix_visitor_username'), 'visitor', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_username'), table_name='visitor')
    op.drop_index(op.f('ix_visitor_email'), table_name='visitor')
    op.drop_table('visitor')
    # ### end Alembic commands ###
