"""visitor refactor

Revision ID: 936f30d7376f
Revises: 4c704b545cc5
Create Date: 2019-11-27 13:54:18.595737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936f30d7376f'
down_revision = '4c704b545cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('visitor', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_visitor_name'), 'visitor', ['name'], unique=False)
    op.create_index(op.f('ix_visitor_phone'), 'visitor', ['phone'], unique=True)
    op.drop_index('ix_visitor_username', table_name='visitor')
    op.drop_column('visitor', 'password_hash')
    op.drop_column('visitor', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_visitor_username', 'visitor', ['username'], unique=1)
    op.drop_index(op.f('ix_visitor_phone'), table_name='visitor')
    op.drop_index(op.f('ix_visitor_name'), table_name='visitor')
    op.drop_column('visitor', 'phone')
    op.drop_column('visitor', 'name')
    # ### end Alembic commands ###
