"""empty message

Revision ID: 9f2d763e9b74
Revises: 4e14dac2e9bb
Create Date: 2019-11-27 15:39:16.846075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2d763e9b74'
down_revision = '4e14dac2e9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor', 'username')
    op.drop_column('visitor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
