"""empty message

Revision ID: aa8b54b8e5b1
Revises: dcc8e94496d1
Create Date: 2019-11-27 18:07:29.478881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8b54b8e5b1'
down_revision = 'dcc8e94496d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('checkInTime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_visitor_checkInTime'), 'visitor', ['checkInTime'], unique=False)
    op.drop_column('visitor', 'username')
    op.drop_column('visitor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_visitor_checkInTime'), table_name='visitor')
    op.drop_column('visitor', 'checkInTime')
    # ### end Alembic commands ###
