"""empty message

Revision ID: f339e1a93df4
Revises: 936f30d7376f
Create Date: 2019-11-27 14:49:27.955472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f339e1a93df4'
down_revision = '936f30d7376f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor', 'username')
    op.drop_column('visitor', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('visitor', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
